CREATE TABLE IF NOT EXISTS cat (
  id SERIAL PRIMARY KEY ,
  name VARCHAR(100) NOT NULL ,
  age INTEGER NOT NULL );

CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY ,
  name VARCHAR(100) NOT NULL ,
  age INTEGER NOT NULL ,
  admin BOOLEAN NOT NULL ,
  balance DOUBLE PRECISION NOT NULL );
